#ifndef INDEX_HTML_H
#define INDEX_HTML_H

const char INDEX_HTML[] PROGMEM = R"rawliteral(
<!DOCTYPE html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Rocket Motor Test Stand</title><style>
body{background:#111;color:#eee;font-family:Arial,sans-serif;text-align:center;margin:0;padding:18px}h1{margin:4px}.subtitle{color:#aaa}.cards{display:flex;justify-content:center;flex-wrap:wrap}.card{width:250px;background:#222;border-radius:12px;padding:18px;margin:9px;box-shadow:0 0 12px #000}.label{color:#aaa;font-size:14px}.value{font-size:42px;font-weight:bold;margin-top:8px}.state{font-size:24px;color:#00ff80}.description-box{max-width:900px;margin:18px auto;background:#222;border-radius:10px;padding:14px}.description-box input{width:calc(100% - 24px);max-width:760px;padding:12px;border-radius:7px;border:1px solid #555;background:#181818;color:#fff;font-size:16px}.counter{color:#999;font-size:12px;margin-top:5px}.main-btn{width:205px;height:52px;margin:7px;font-size:18px;border:0;border-radius:8px;color:#fff;cursor:pointer}.tare{background:#06c}.start{background:#093}.stop{background:#a00000}.secondary{background:#555}.message{min-height:24px;color:#ffd166;margin:10px}.storage,.import-box,.history{max-width:1100px;margin:18px auto;background:#1b1b1b;border-radius:12px;padding:16px;box-shadow:0 0 12px #000}.import-box input{max-width:100%}.table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse;table-layout:fixed;min-width:980px}th,td{padding:11px 8px;border-bottom:1px solid #383838;vertical-align:middle}th{color:#aaa}th:nth-child(1),td:nth-child(1){width:70px;text-align:left}th:nth-child(2),td:nth-child(2){width:225px;text-align:left;white-space:nowrap}th:nth-child(3),td:nth-child(3){width:300px;text-align:left;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}th:nth-child(4),td:nth-child(4){width:100px;text-align:right}th:nth-child(5),td:nth-child(5){width:90px;text-align:right}th:nth-child(6),td:nth-child(6){width:210px;text-align:center;white-space:nowrap}.action{display:inline-flex;align-items:center;justify-content:center;width:34px;height:32px;margin:2px;border:0;border-radius:6px;background:#444;color:#fff;text-decoration:none;cursor:pointer;font-size:15px}.delete{background:#9b1c1c}.edit{background:#755b00}.empty{text-align:center!important;color:#999}.storage-low{color:#ffd166}.storage-critical{color:#ff8080}.footer{margin:30px;color:#888;font-size:13px}@media(max-width:700px){body{padding:8px}.card{width:42%;min-width:135px}.value{font-size:34px}.main-btn{width:46%;font-size:16px}}
</style></head><body><h1>🚀 Rocket Motor Test Stand</h1><div class="subtitle">ESP32-S3 + HX711 — 80 SPS</div><div class="cards"><div class="card"><div class="label">STATUS</div><div id="status" class="state">IDLE</div></div><div class="card"><div class="label">FORÇA</div><div id="force" class="value">0.0</div><div>gramas</div></div><div class="card"><div class="label">PICO</div><div id="peak" class="value">0.0</div><div>gramas</div></div></div>
<div class="description-box"><div class="label">DESCRIÇÃO DO ENSAIO</div><input id="description" maxlength="50" placeholder="Ex.: KNSU 65/35, bocal 6 mm, lote 03" oninput="countDescription()"><div id="descriptionCount" class="counter">0/50</div></div>
<button class="main-btn tare" onclick="tareScale()">Tara</button><button class="main-btn start" onclick="startTest()">Iniciar ensaio</button><button class="main-btn stop" onclick="stopTest()">Parar</button><button class="main-btn secondary" onclick="loadHistory()">Atualizar histórico</button><div id="message" class="message"></div>
<div class="storage"><strong>Armazenamento:</strong> <span id="storageText">Carregando...</span></div>
<div class="import-box"><h2>Restaurar curva salva</h2><p>Selecione um backup <strong>.rts</strong> ou um CSV exportado por este equipamento.</p><input id="importFile" type="file" accept=".rts,.csv,text/csv,application/octet-stream"> <button class="main-btn secondary" onclick="importCampaign()">Importar</button></div>
<section class="history"><h2>Histórico de ensaios</h2><div class="table-wrap"><table><thead><tr><th>Ensaio</th><th>Data e hora</th><th>Descrição</th><th>Pico</th><th>Amostras</th><th>Ações</th></tr></thead><tbody id="historyBody"><tr><td colspan="6" class="empty">Carregando...</td></tr></tbody></table></div></section><div class="footer">Rocket Motor Static Test Stand</div>
<script>
let previousState='',refreshBusy=false,failures=0,historyCampaigns=[];const $=id=>document.getElementById(id);function msg(t){$('message').textContent=t}function pad(n){return String(n).padStart(2,'0')}function browserDateTime(){const d=new Date(),o=-d.getTimezoneOffset(),s=o>=0?'+':'-',hh=pad(Math.floor(Math.abs(o)/60)),mm=pad(Math.abs(o)%60);return d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate())+'T'+pad(d.getHours())+':'+pad(d.getMinutes())+':'+pad(d.getSeconds())+s+hh+':'+mm}function displayDate(v){return !v||v==='unknown'?'Não informada':v.replace('T',' ')}function formatBytes(v){if(v<1024)return v+' B';if(v<1048576)return(v/1024).toFixed(1)+' KB';return(v/1048576).toFixed(2)+' MB'}function countDescription(){$('descriptionCount').textContent=$('description').value.length+'/50'}function updateStorage(j){const p=j.storageTotal?100*j.storageUsed/j.storageTotal:0,e=$('storageText');e.textContent=formatBytes(j.storageUsed)+' usados de '+formatBytes(j.storageTotal)+' — '+formatBytes(j.storageFree)+' livres ('+p.toFixed(1)+'%)';e.className=p>=90?'storage-critical':p>=80?'storage-low':''}
async function refresh(){if(refreshBusy)return;refreshBusy=true;try{const r=await fetch('/status',{cache:'no-store'});if(!r.ok)throw 0;const j=await r.json();failures=0;$('status').textContent=j.state;$('force').textContent=Number(j.force).toFixed(1);$('peak').textContent=Number(j.peak).toFixed(1);updateStorage(j);if(previousState&&previousState!=='IDLE'&&j.state==='IDLE')loadHistory();previousState=j.state}catch(e){if(++failures>=3)msg('Sem comunicação com o equipamento')}finally{refreshBusy=false}}
async function startTest(){try{const r=await fetch('/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({datetime:browserDateTime(),description:$('description').value.trim()})});msg(await r.text())}catch(e){msg('Falha ao iniciar o ensaio')}}async function tareScale(){try{const r=await fetch('/tare',{method:'POST'});msg(await r.text())}catch(e){msg('Falha ao executar tara')}}async function stopTest(){try{const r=await fetch('/stop',{method:'POST'});msg(await r.text())}catch(e){msg('Falha ao parar o ensaio')}}
async function editDescription(id){const c=historyCampaigns.find(x=>x.id===id),v=prompt('Descrição do ensaio (máximo 50 caracteres):',c?c.description||'':'');if(v===null)return;const r=await fetch('/campaign/description?id='+id,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({description:v.slice(0,50)})});const j=await r.json();msg(j.message||'Operação concluída');if(r.ok)loadHistory()}async function deleteTest(id){if(!confirm('Apagar definitivamente o ensaio #'+id+'?'))return;const r=await fetch('/campaign/delete?id='+id,{method:'POST'}),j=await r.json();msg(j.message||'Operação concluída');if(r.ok){loadHistory();refresh()}}
async function loadHistory(){const b=$('historyBody');try{const r=await fetch('/history',{cache:'no-store'}),d=await r.json();historyCampaigns=d.campaigns||[];if(!d.campaigns.length){b.innerHTML='<tr><td colspan="6" class="empty">Nenhum ensaio gravado</td></tr>';return}b.innerHTML=d.campaigns.map(c=>'<tr><td>#'+c.id+'</td><td>'+displayDate(c.datetime)+'</td><td title="'+(c.description||'')+'">'+(c.description||'<em>Sem descrição</em>')+'</td><td>'+Number(c.peak).toFixed(1)+' g</td><td>'+c.samples+'</td><td><a class="action" href="/test?id='+c.id+'" title="Análise e gráfico">📈</a><a class="action" href="/csv?id='+c.id+'" title="CSV">📄</a><a class="action" href="/rts?id='+c.id+'" title="Backup RTS">💾</a><button class="action edit" onclick="editDescription('+c.id+')" title="Editar descrição">✏</button><button class="action delete" onclick="deleteTest('+c.id+')" title="Apagar">🗑</button></td></tr>').join('')}catch(e){b.innerHTML='<tr><td colspan="6" class="empty">Falha ao carregar o histórico</td></tr>'}}
async function importCampaign(){const f=$('importFile').files[0];if(!f){msg('Selecione um arquivo .rts ou .csv');return}try{let r;if(f.name.toLowerCase().endsWith('.csv')){r=await fetch('/campaign/import-csv',{method:'POST',headers:{'Content-Type':'text/csv'},body:await f.text()})}else{const form=new FormData();form.append('file',f);r=await fetch('/campaign/import-rts',{method:'POST',body:form})}const j=await r.json();msg(j.message||'Importação concluída');if(r.ok){$('importFile').value='';loadHistory();refresh()}}catch(e){msg('Falha ao importar o arquivo')}}setInterval(refresh,500);refresh();loadHistory();countDescription();
</script></body></html>
)rawliteral";

const char TEST_HTML[] PROGMEM = R"rawliteral(
<!DOCTYPE html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Análise do ensaio</title><style>
body{background:#111;color:#eee;font-family:Arial,sans-serif;margin:0;padding:16px}.wrap{max-width:1180px;margin:auto}.top{display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap;align-items:center}.buttons a,.buttons button{display:inline-block;background:#444;color:#fff;text-decoration:none;border:0;border-radius:7px;padding:10px 13px;margin:3px;cursor:pointer}.description{font-size:19px;color:#ffd166;margin:6px 0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(155px,1fr));gap:10px;margin:18px 0}.card{background:#222;border-radius:10px;padding:14px}.label{font-size:12px;color:#aaa}.value{font-size:23px;font-weight:bold;margin-top:6px}.controls{background:#222;border-radius:10px;padding:12px;margin:12px 0}.controls select{padding:8px;background:#181818;color:#fff;border:1px solid #555;border-radius:5px}.chartbox{background:#181818;border-radius:12px;padding:10px;box-shadow:0 0 12px #000}canvas{width:100%;height:500px;display:block;touch-action:none}.hint{text-align:center;color:#999;font-size:13px;margin-top:8px}.error{color:#ff8080;padding:20px;text-align:center}
</style></head><body><div class="wrap"><div class="top"><div><h1 id="title">Ensaio</h1><div id="description" class="description"></div><div id="datetime">Carregando...</div></div><div class="buttons"><a href="/">Voltar</a><a id="csv" href="#">CSV</a><a id="rts" href="#">Backup RTS</a><button onclick="editDescription()">Editar descrição</button><button onclick="deleteCurrent()" style="background:#941d1d">Apagar</button></div></div>
<div class="grid"><div class="card"><div class="label">PICO</div><div id="peak" class="value">-</div></div><div class="card"><div class="label">IMPULSO POSITIVO</div><div id="impulse" class="value">-</div></div><div class="card"><div class="label">TEMPO DE IGNIÇÃO</div><div id="ignition" class="value">-</div></div><div class="card"><div class="label">INSTANTE DO PICO</div><div id="peakTime" class="value">-</div></div><div class="card"><div class="label">TEMPO ATÉ O PICO</div><div id="toPeak" class="value">-</div></div><div class="card"><div class="label">TEMPO DE QUEIMA</div><div id="burn" class="value">-</div></div><div class="card"><div class="label">FORÇA MÉDIA NA QUEIMA</div><div id="burnAverage" class="value">-</div></div><div class="card"><div class="label">TAXA REAL</div><div id="rate" class="value">-</div></div><div class="card"><div class="label">TAXA MÁXIMA DE SUBIDA</div><div id="maxRise" class="value">-</div></div><div class="card"><div class="label">DURAÇÃO REGISTRADA</div><div id="duration" class="value">-</div></div><div class="card"><div class="label">AMOSTRAS</div><div id="samples" class="value">-</div></div></div>
<div class="controls"><strong>Sobrepor outro ensaio:</strong> <select id="compare"><option value="">Nenhum</option></select> <button onclick="loadComparison()">Comparar</button> <button onclick="resetZoom()">Restaurar zoom</button></div><div class="chartbox"><canvas id="chart"></canvas><div class="hint">Área preenchida = impulso positivo. Linhas verticais = ignição, pico e fim da queima. Arraste horizontalmente para ampliar.</div></div><div id="error" class="error"></div></div>
<script>
const id=new URLSearchParams(location.search).get('id'),canvas=document.getElementById('chart'),ctx=canvas.getContext('2d');let points=[],comparePoints=[],info=null,viewStart=0,viewEnd=0,dragStart=null;const $=x=>document.getElementById(x);function fmtDate(v){return !v||v==='unknown'?'Não informada':v.replace('T',' ')}function resize(){const d=devicePixelRatio||1,r=canvas.getBoundingClientRect();canvas.width=Math.max(320,Math.floor(r.width*d));canvas.height=Math.max(300,Math.floor(r.height*d));ctx.setTransform(d,0,0,d,0,0);draw()}window.addEventListener('resize',resize);
function drawCurve(data,x,y,color,fill){if(data.length<2)return;if(fill){ctx.fillStyle='rgba(0,208,132,.18)';ctx.beginPath();ctx.moveTo(x(data[0][0]),y(0));data.forEach(p=>ctx.lineTo(x(p[0]),y(Math.max(0,p[1]))));ctx.lineTo(x(data[data.length-1][0]),y(0));ctx.closePath();ctx.fill()}ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();data.forEach((p,i)=>i?ctx.lineTo(x(p[0]),y(p[1])):ctx.moveTo(x(p[0]),y(p[1])));ctx.stroke()}
function draw(){const w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);if(points.length<2)return;const a=Math.max(0,viewStart),b=Math.min(points.length-1,viewEnd),main=points.slice(a,b+1),all=comparePoints.length?main.concat(comparePoints):main;let ymin=0,ymax=1;all.forEach(p=>{ymin=Math.min(ymin,p[1]);ymax=Math.max(ymax,p[1])});const pad={l:62,r:18,t:18,b:42},cw=w-pad.l-pad.r,ch=h-pad.t-pad.b,t0=main[0][0],t1=main[main.length-1][0],x=t=>pad.l+(t-t0)/(t1-t0||1)*cw,y=v=>pad.t+(ymax-v)/(ymax-ymin||1)*ch;ctx.strokeStyle='#444';ctx.fillStyle='#aaa';ctx.font='12px Arial';for(let i=0;i<=5;i++){const yy=pad.t+i*ch/5,val=ymax-i*(ymax-ymin)/5;ctx.beginPath();ctx.moveTo(pad.l,yy);ctx.lineTo(w-pad.r,yy);ctx.stroke();ctx.fillText(val.toFixed(0)+' g',4,yy+4)}for(let i=0;i<=5;i++){const xx=pad.l+i*cw/5,val=(t0+i*(t1-t0)/5)/1e6;ctx.beginPath();ctx.moveTo(xx,pad.t);ctx.lineTo(xx,h-pad.b);ctx.stroke();ctx.fillText(val.toFixed(1)+' s',xx-12,h-15)}drawCurve(main,x,y,'#00d084',true);if(comparePoints.length)drawCurve(comparePoints,x,y,'#ff9f43',false);if(info){[['Ignição',info.ignitionTime,'#4da6ff'],['Pico',info.peakTime,'#ff5c5c'],['Fim',info.ignitionTime+info.burnTime,'#ffd166']].forEach(m=>{const us=m[1]*1e6;if(us<t0||us>t1)return;const xx=x(us);ctx.strokeStyle=m[2];ctx.beginPath();ctx.moveTo(xx,pad.t);ctx.lineTo(xx,h-pad.b);ctx.stroke();ctx.fillStyle=m[2];ctx.fillText(m[0],xx+3,pad.t+13)})}}
function indexAt(px){const r=Math.max(0,Math.min(1,(px-62)/(canvas.clientWidth-80)));return Math.round(viewStart+r*(viewEnd-viewStart))}canvas.addEventListener('pointerdown',e=>{dragStart=e.offsetX;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointerup',e=>{if(dragStart===null)return;const a=indexAt(dragStart),b=indexAt(e.offsetX);dragStart=null;if(Math.abs(b-a)>4){viewStart=Math.min(a,b);viewEnd=Math.max(a,b);draw()}});canvas.addEventListener('dblclick',resetZoom);function resetZoom(){viewStart=0;viewEnd=Math.max(0,points.length-1);draw()}
async function loadComparison(){const cid=$('compare').value;if(!cid){comparePoints=[];draw();return}const r=await fetch('/campaign/data?id='+cid,{cache:'no-store'}),d=await r.json();comparePoints=d.samples||[];draw()}
async function editDescription(){const v=prompt('Descrição do ensaio:',info.description||'');if(v===null)return;const r=await fetch('/campaign/description?id='+id,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({description:v.slice(0,50)})});if(r.ok)load()}async function deleteCurrent(){if(!confirm('Apagar definitivamente este ensaio?'))return;const r=await fetch('/campaign/delete?id='+id,{method:'POST'});if(r.ok)location.href='/'}
async function load(){if(!id){$('error').textContent='Identificador não informado';return}$('csv').href='/csv?id='+id;$('rts').href='/rts?id='+id;try{const [ir,dr,hr]=await Promise.all([fetch('/campaign?id='+id,{cache:'no-store'}),fetch('/campaign/data?id='+id,{cache:'no-store'}),fetch('/history',{cache:'no-store'})]);if(!ir.ok||!dr.ok)throw 0;info=await ir.json();points=(await dr.json()).samples||[];const hist=await hr.json();$('compare').innerHTML='<option value="">Nenhum</option>'+hist.campaigns.filter(c=>String(c.id)!==String(id)).map(c=>'<option value="'+c.id+'">#'+c.id+' — '+(c.description||'Sem descrição')+'</option>').join('');$('title').textContent='Ensaio #'+info.id;$('description').textContent=info.description||'Sem descrição';$('datetime').textContent=fmtDate(info.datetime);$('peak').textContent=Number(info.peak).toFixed(1)+' g';$('impulse').textContent=Number(info.impulse).toFixed(1)+' g·s';$('ignition').textContent=Number(info.ignitionTime).toFixed(3)+' s';$('peakTime').textContent=Number(info.peakTime).toFixed(3)+' s';$('toPeak').textContent=Number(info.timeToPeak).toFixed(3)+' s';$('burn').textContent=Number(info.burnTime).toFixed(3)+' s';$('burnAverage').textContent=Number(info.burnAverage).toFixed(1)+' g';$('rate').textContent=Number(info.sampleRate).toFixed(1)+' SPS';$('maxRise').textContent=Number(info.maxRiseRate).toFixed(1)+' g/s';$('duration').textContent=Number(info.duration).toFixed(3)+' s';$('samples').textContent=info.samples;resetZoom();resize()}catch(e){$('error').textContent='Não foi possível carregar este ensaio.'}}load();
</script></body></html>
)rawliteral";

#endif
